<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="en_GB">
<context>
    <name>About</name>
    <message>
        <location filename="about.ui" line="29"/>
        <source>CluVis - O programie</source>
        <translation>CluVis - About</translation>
    </message>
    <message>
        <location filename="about.ui" line="41"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p align=&quot;center&quot;&gt;&lt;span style=&quot; font-size:16pt; font-weight:600;&quot;&gt;CluVis - Wizualizator Skupień&lt;/span&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p align=&quot;center&quot;&gt;&lt;span style=&quot; font-size:16pt; font-weight:600;&quot;&gt;CluVis - Cluster Visualizator&lt;/span&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="about.ui" line="54"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p align=&quot;justify&quot;&gt;Niniejszy program służy do generowania oraz interaktywnego wizualizowania skupień reguł. Aplikacja operuje na regułach wygenerowanych przez system RSES, przy pomocy algorytmu LEM2. Utworzona w ten sposób reguła może być określona atrybutami ciągłymi oraz jakościowymi.&lt;br/&gt;&lt;br/&gt;Powstał on jako projekt realizowany w ramach pracy inżynierkiej autora zatytułowanej &amp;quot;Wizualizacja struktur hierarchicznych dla regułowych baz wiedzy&amp;quot;. &lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p align=&quot;justify&quot;&gt;CluVis is an application designed to group and generate responsive visualization of rules clusters. It operates on rules generated by RSES using LEM2 algorithm. Rule created that way can have both numerical and symbolic attributes.&lt;br/&gt;&lt;br/&gt;CluVis was created as part of author&apos;s engineer&apos;s thesis entitled &amp;quot;Visualization of hierarchical structures for rule-based knowledge bases&amp;quot;. &lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="about.ui" line="70"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Autor:&lt;/span&gt; Tomasz Rybotycki (rybotyckitomasz@gmail.com)&lt;br/&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Promotor: &lt;/span&gt;Dr Agnieszka Nowak-Brzezińska&lt;br/&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Opiekun pracy: &lt;/span&gt;Dr Tomasz Xięski&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Author:&lt;/span&gt; Eng. Tomasz Rybotycki (tomevek@gmail.com)&lt;br/&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Promoter: &lt;/span&gt;Ph.D. Agnieszka Nowak-Brzezińska&lt;br/&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Supervisor: &lt;/span&gt;Ph.D. Tomasz Xięski&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
</context>
<context>
    <name>MainWindow</name>
    <message>
        <location filename="mainwindow.ui" line="29"/>
        <source>CluVis - Wizualizator Skupień</source>
        <translation>CluVis - Cluster Visualizator</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="40"/>
        <source>Wizualizacja</source>
        <translation>Visualization</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="100"/>
        <source>Ustawienia ogólne</source>
        <translation>General settings</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="115"/>
        <source>Typ grupowanych obiektów:</source>
        <translation>Grouped objects type:</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="122"/>
        <source>&lt;b&gt;RSES LEM2 Rules&lt;/b&gt;</source>
        <translation>RSES LEM2 Rules</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="129"/>
        <source>Algorytm grupowania:</source>
        <translation>Grouping algorithm:</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="136"/>
        <source>&lt;b&gt;Klasyczny hierarchiczny algorytm grupowania&lt;/b&gt;</source>
        <translation>Classic hierarchic grouping algorithm</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="143"/>
        <source>Baza reguł:</source>
        <translation>Object base:</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="152"/>
        <source>&lt;b&gt;Nie wczytano.&lt;/b&gt;</source>
        <translation>&lt;b&gt;Not loaded.&lt;/b&gt;</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="159"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;(Niepogrupowana) &lt;/span&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translatorcomment>&lt;b&gt;(Niepogrupowana)&lt;/b&gt;</translatorcomment>
        <translation>&lt;b&gt;(Ungrouped)&lt;/b&gt;</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="168"/>
        <source>Liczba reguł w bazie:</source>
        <translation>Objects number:</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="175"/>
        <source>&lt;b&gt;0.&lt;/b&gt;</source>
        <translation>&lt;b&gt; 0.&lt;/b&gt;</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="182"/>
        <source>Grupowanie reguł ze względu na:</source>
        <translation>Grouped part:</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="192"/>
        <source>Warunki</source>
        <translation>Conditions</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="197"/>
        <source>Konkluzje</source>
        <translation>Conclusions</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="223"/>
        <source>Miara odległości między obiektami:</source>
        <translation>Inter-object distance measure:</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="239"/>
        <source>Miara Gowera</source>
        <translation>Gower&apos;s measure</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="244"/>
        <source>Simple Similarity</source>
        <translation>Simple Similarity</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="249"/>
        <source>Weighted Similarity</source>
        <translation>Weighted Similarity</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="272"/>
        <source>Miara odległości międzyklastrowej:</source>
        <translation>Inter-cluster similarity measure:</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="282"/>
        <source>Pojedynczego połączenia</source>
        <translation>Single Link</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="287"/>
        <source>Całkowitego połączenia</source>
        <translation>Complete link</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="292"/>
        <source>Średniej grupowej</source>
        <translation>Average link</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="297"/>
        <source>Środków ciężkości</source>
        <translation>Centroid link</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="323"/>
        <source>Na ilu skupieniach zakończyć grupowanie?
Liczba skupień musi być mniejsza lub równa
liczbie obiektów w bazie.</source>
        <translation>When to finish grouping?
Clusters number must be lower or equal
to number of objects in base.</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="362"/>
        <source>Algorytm wizualizacji:</source>
        <translation>Visualization algorithm:</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="372"/>
        <source>RT Slice And Dice</source>
        <translation>RT Slice And Dice</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="377"/>
        <source>Circular Treemap</source>
        <translation>Circular Treemap</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="403"/>
        <source>Wizualizuj wszystkie poziomy hierarchii.</source>
        <translation>Visualize all hierarchy levels.</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="410"/>
        <source>Szukaj optymalnych grupowań.</source>
        <oldsource>Szukaj optymalnych grupowań</oldsource>
        <translation>Search for optimal groupings.</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="419"/>
        <source>Grupuj</source>
        <translation>Group</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="426"/>
        <source>Wizualizuj</source>
        <translation>Visualize</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="458"/>
        <source>Ustawienia szczegółowe</source>
        <translation>Advanced settings</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="508"/>
        <source>Dziennik zdarzeń</source>
        <translation>Log</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="514"/>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;MS Shell Dlg 2&apos;; font-size:8.25pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Log...&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation></translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="539"/>
        <source>Plik</source>
        <translation>File</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="550"/>
        <source>Pomoc</source>
        <translation>Help</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="556"/>
        <source>Widok</source>
        <translation>View</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="560"/>
        <source>Język</source>
        <translation>Language</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="576"/>
        <source>Wczytaj bazę obiektów</source>
        <translation>Load object base</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="581"/>
        <source>Zakończ program</source>
        <translation>Quit</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="586"/>
        <source>Informacje o programie</source>
        <translation>About</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="591"/>
        <source>Zapisz wizualizację</source>
        <translation>Save visualization</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="596"/>
        <source>Generuj raport</source>
        <translation>Generate raport</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="601"/>
        <source>Angielski</source>
        <translation>English</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="606"/>
        <source>Polski</source>
        <translation>Polish</translation>
    </message>
    <message>
        <location filename="mainwindow.cpp" line="155"/>
        <source>Wybierz bazę</source>
        <translation>Select base</translation>
    </message>
    <message>
        <location filename="mainwindow.cpp" line="155"/>
        <source>Pliki reguł(*.rul);; Pliki tekstowe (*.txt)</source>
        <translation>Rule files(*.rul);; Text files (*.txt)</translation>
    </message>
</context>
<context>
    <name>clusterInfo_RSESRules</name>
    <message>
        <location filename="clusterinfo_rsesrules.ui" line="32"/>
        <source>Dialog</source>
        <translation>titlePlaceholder</translation>
    </message>
    <message>
        <location filename="clusterinfo_rsesrules.ui" line="48"/>
        <source>Liczba reguł w skupieniu:</source>
        <translation>Number of rules in cluster:</translation>
    </message>
    <message>
        <location filename="clusterinfo_rsesrules.ui" line="61"/>
        <source>liczba reguł</source>
        <translation>rulesNumPlaceholder</translation>
    </message>
    <message>
        <location filename="clusterinfo_rsesrules.ui" line="95"/>
        <source>Wizualizuj!</source>
        <translation>Visualize!</translation>
    </message>
    <message>
        <location filename="clusterinfo_rsesrules.ui" line="110"/>
        <source>Reprezentant skupienia:</source>
        <translation>Cluster&apos;s representative:</translation>
    </message>
    <message>
        <location filename="clusterinfo_rsesrules.ui" line="135"/>
        <source>reprezentant</source>
        <translation>repPlaceholder</translation>
    </message>
    <message>
        <location filename="clusterinfo_rsesrules.ui" line="158"/>
        <source>Atrybuty warunkowe występujące w skupieniu:</source>
        <translation>Conditional attributes occuring in cluster:</translation>
    </message>
    <message>
        <location filename="clusterinfo_rsesrules.ui" line="177"/>
        <location filename="clusterinfo_rsesrules.ui" line="206"/>
        <source>Atrybuty</source>
        <translation>attrPlaceholder</translation>
    </message>
    <message>
        <location filename="clusterinfo_rsesrules.ui" line="193"/>
        <source>Atrybuty decyzyjne występujące w skupieniu:</source>
        <translation>Decisional attributes occuring in cluster:</translation>
    </message>
    <message>
        <location filename="clusterinfo_rsesrules.ui" line="226"/>
        <source>Najdłuższa reguła:</source>
        <translation>Longest rule:</translation>
    </message>
    <message>
        <location filename="clusterinfo_rsesrules.ui" line="233"/>
        <location filename="clusterinfo_rsesrules.ui" line="262"/>
        <source>reguła</source>
        <translation>rulePlaceholder</translation>
    </message>
    <message>
        <location filename="clusterinfo_rsesrules.ui" line="249"/>
        <source>Najkrótsza reguła:</source>
        <translation>Shortest rule:</translation>
    </message>
    <message>
        <location filename="clusterinfo_rsesrules.ui" line="284"/>
        <source>Najczęstsza decyzja:</source>
        <translation>Most common decision:</translation>
    </message>
    <message>
        <location filename="clusterinfo_rsesrules.ui" line="297"/>
        <location filename="clusterinfo_rsesrules.ui" line="327"/>
        <source>decyzja</source>
        <translation>decisionPlaceholder</translation>
    </message>
    <message>
        <location filename="clusterinfo_rsesrules.ui" line="314"/>
        <source>Najrzadsza decyzja:</source>
        <translation>Least common decision:</translation>
    </message>
    <message>
        <location filename="clusterinfo_rsesrules.ui" line="344"/>
        <source>Wsparcie reguły:</source>
        <translation>Rule&apos;s support (for rules only):</translation>
    </message>
    <message>
        <location filename="clusterinfo_rsesrules.ui" line="357"/>
        <source>0</source>
        <translation>0</translation>
    </message>
    <message>
        <location filename="clusterinfo_rsesrules.cpp" line="19"/>
        <source>Informacje o skupieniu:</source>
        <translation>Informations about cluster:</translation>
    </message>
</context>
</TS>
