<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="en_GB">
<context>
    <name>About</name>
    <message>
        <location filename="Forms/about.ui" line="29"/>
        <source>CluVis - O programie</source>
        <translation>CluVis - About</translation>
    </message>
    <message>
        <location filename="Forms/about.ui" line="41"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p align=&quot;center&quot;&gt;&lt;span style=&quot; font-size:16pt; font-weight:600;&quot;&gt;CluVis - Wizualizator Skupień&lt;/span&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p align=&quot;center&quot;&gt;&lt;span style=&quot; font-size:16pt; font-weight:600;&quot;&gt;CluVis - Cluster Visualizer&lt;/span&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="Forms/about.ui" line="54"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p align=&quot;justify&quot;&gt;Niniejszy program służy do generowania oraz interaktywnego wizualizowania skupień reguł. Aplikacja operuje na regułach wygenerowanych przez system RSES, przy pomocy algorytmu LEM2. Utworzona w ten sposób reguła może być określona atrybutami ciągłymi oraz jakościowymi.&lt;br/&gt;&lt;br/&gt;Powstał on jako projekt realizowany w ramach pracy inżynierkiej autora zatytułowanej &amp;quot;Wizualizacja struktur hierarchicznych dla regułowych baz wiedzy&amp;quot;. &lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p align=&quot;justify&quot;&gt;CluVis is an application designed to group and generate responsive visualization of rules clusters. It operates on rules generated by RSES using LEM2 algorithm. Rule created that way can have both numerical and symbolic attributes.&lt;br/&gt;&lt;br/&gt;CluVis was created as part of author&apos;s engineer&apos;s thesis entitled &amp;quot;Visualization of hierarchical structures for rule-based knowledge bases&amp;quot;. &lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="Forms/about.ui" line="70"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Autor:&lt;/span&gt; Tomasz Rybotycki (rybotyckitomasz@gmail.com)&lt;br/&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Promotor: &lt;/span&gt;Dr Agnieszka Nowak-Brzezińska&lt;br/&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Opiekun pracy: &lt;/span&gt;Dr Tomasz Xięski&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Author:&lt;/span&gt; Eng. Tomasz Rybotycki (tomevek@gmail.com)&lt;br/&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Promoter: &lt;/span&gt;Ph.D. Agnieszka Nowak-Brzezińska&lt;br/&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Supervisor: &lt;/span&gt;Ph.D. Tomasz Xięski&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
</context>
<context>
    <name>MainWindow</name>
    <message>
        <location filename="Forms/mainwindow.ui" line="29"/>
        <source>CluVis - Wizualizator Skupień</source>
        <translation>CluVis - Cluster Visualizer</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="761"/>
        <source>Wizualizacja</source>
        <translation>Visualization</translation>
    </message>
    <message>
        <source>Ustawienia ogólne</source>
        <translation type="vanished">General settings</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="586"/>
        <source>Typ grupowanych obiektów:</source>
        <translation>Grouped objects type:</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="593"/>
        <source>&lt;b&gt;RSES LEM2 Rules&lt;/b&gt;</source>
        <translation>RSES LEM2 Rules</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="79"/>
        <source>Algorytm grupowania:</source>
        <translation>Grouping algorithm:</translation>
    </message>
    <message>
        <source>&lt;b&gt;Klasyczny hierarchiczny algorytm grupowania&lt;/b&gt;</source>
        <translation type="vanished">Classic hierarchic grouping algorithm</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="681"/>
        <source>Baza reguł:</source>
        <translation>Object base:</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="690"/>
        <source>&lt;b&gt;Nie wczytano.&lt;/b&gt;</source>
        <translation>&lt;b&gt;Not loaded.&lt;/b&gt;</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="697"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;(Niepogrupowana) &lt;/span&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translatorcomment>&lt;b&gt;(Niepogrupowana)&lt;/b&gt;</translatorcomment>
        <translation>&lt;b&gt;(Ungrouped)&lt;/b&gt;</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="706"/>
        <source>Liczba reguł w bazie:</source>
        <translation>Objects number:</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="713"/>
        <source>&lt;b&gt;0.&lt;/b&gt;</source>
        <translation>&lt;b&gt; 0.&lt;/b&gt;</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="600"/>
        <source>Grupowanie reguł ze względu na:</source>
        <translation>Grouped part:</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="616"/>
        <source>Warunki</source>
        <translation>Conditions</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="621"/>
        <source>Konkluzje</source>
        <translation>Conclusions</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="99"/>
        <source>Miara odległości między obiektami:</source>
        <translation>Inter-object distance measure:</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="115"/>
        <source>Miara Gowera</source>
        <translation>Gower&apos;s measure</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="120"/>
        <source>Simple Similarity</source>
        <translation>Simple Similarity</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="125"/>
        <source>Weighted Similarity</source>
        <translation>Weighted Similarity</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="178"/>
        <source>Miara odległości międzyklastrowej:</source>
        <translation>Inter-cluster similarity measure:</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="194"/>
        <source>Pojedynczego połączenia</source>
        <translation>Single Link</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="199"/>
        <source>Całkowitego połączenia</source>
        <translation>Complete link</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="204"/>
        <source>Średniej grupowej</source>
        <translation>Average link</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="209"/>
        <source>Środków ciężkości</source>
        <translation>Centroid link</translation>
    </message>
    <message>
        <source>Na ilu skupieniach zakończyć grupowanie?
Liczba skupień musi być mniejsza lub równa
liczbie obiektów w bazie.</source>
        <translation type="vanished">When to finish grouping?
Clusters number must be lower or equal
to number of objects in base.</translation>
    </message>
    <message>
        <source>Procent obiektów, zawierających atrybut, aby był on brany pod uwagę przy tworzeniu reprezentanta:</source>
        <translation type="vanished">Objects containing attribure percent, for attribute to be added to clusters representative:</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="332"/>
        <location filename="Forms/mainwindow.ui" line="785"/>
        <source>Algorytm wizualizacji:</source>
        <translation>Visualization algorithm:</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="348"/>
        <source>RT Slice And Dice</source>
        <translation>RT Slice And Dice</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="353"/>
        <location filename="Forms/mainwindow.ui" line="804"/>
        <source>Circular Treemap</source>
        <translation>Circular Treemap</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="278"/>
        <source>Wizualizuj wszystkie poziomy hierarchii.</source>
        <translation>Visualize all hierarchy levels.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="285"/>
        <source>Szukaj optymalnych grupowań.</source>
        <oldsource>Szukaj optymalnych grupowań</oldsource>
        <translation>Search for optimal groupings.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="745"/>
        <source>Grupuj</source>
        <translation>Group</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="752"/>
        <location filename="Forms/mainwindow.ui" line="833"/>
        <source>Wizualizuj</source>
        <translation>Visualize</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="574"/>
        <source>Ustawienia szczegółowe</source>
        <translation>Advanced settings</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="40"/>
        <source>Ustawienia</source>
        <translation>Settings</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="70"/>
        <source>Ustawienia ogólne grupowania</source>
        <translation>General grouping settings</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="92"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Klasyczny AHC&lt;/span&gt;&lt;/p&gt;&lt;p&gt;&lt;br/&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Classical AHC&lt;/span&gt;&lt;/p&gt;&lt;p&gt;&lt;br/&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="130"/>
        <source>OF</source>
        <translation>OF</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="135"/>
        <source>IOF</source>
        <translation>IOF</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="140"/>
        <source>Goodall1</source>
        <translation>Goodall1</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="145"/>
        <source>Goodall2</source>
        <translation>Goodall2</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="150"/>
        <source>Goodall3</source>
        <translation>Goodall3</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="155"/>
        <source>Goodall4</source>
        <translation>Goodall4</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="235"/>
        <source>Oczekiwana liczba skupień:</source>
        <translation>Expected clusters number:</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="326"/>
        <location filename="Forms/mainwindow.ui" line="779"/>
        <source>Ustawienia wizualizacji</source>
        <translation>Visualization settings</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="379"/>
        <source>Margines prostokątów (px):</source>
        <translation>Rectangles margin (px):</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="441"/>
        <source>Ustawienia reprezentanta</source>
        <translation>Representative settings</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="447"/>
        <source>Strategia tworzenia reprezentanta:</source>
        <translation>Representative creation strategy:</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="469"/>
        <source>Progowa</source>
        <translation>Threshold</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="474"/>
        <source>TFIDF</source>
        <translation>TFIDF</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="497"/>
        <source>Występowanie atrybutu (%):</source>
        <translation>Attribute occurence (%):</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="675"/>
        <source>Informacje o bazie</source>
        <translation>Object base information</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="799"/>
        <source>RT Slice and Dice</source>
        <translation>RT Slice and Dice</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="812"/>
        <source>Margines obiektów (px):</source>
        <translation>Objects margin (px):</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="873"/>
        <source>Dziennik zdarzeń</source>
        <translation>Log</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="879"/>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;MS Shell Dlg 2&apos;; font-size:8.25pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;br /&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <oldsource>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;MS Shell Dlg 2&apos;; font-size:8.25pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Log...&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</oldsource>
        <translation></translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="904"/>
        <source>Plik</source>
        <translation>File</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="915"/>
        <source>Pomoc</source>
        <translation>Help</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="921"/>
        <source>Widok</source>
        <translation>View</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="925"/>
        <source>Język</source>
        <translation>Language</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="941"/>
        <source>Wczytaj bazę obiektów</source>
        <translation>Load object base</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="946"/>
        <source>Zakończ program</source>
        <translation>Quit</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="951"/>
        <source>Informacje o programie</source>
        <translation>About</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="956"/>
        <source>Zapisz wizualizację</source>
        <translation>Save visualization</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="961"/>
        <source>Generuj raport</source>
        <translation>Generate raport</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="966"/>
        <source>Angielski</source>
        <translation>English</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.ui" line="971"/>
        <source>Polski</source>
        <translation>Polish</translation>
    </message>
    <message>
        <source>Wybierz bazę</source>
        <translation type="vanished">Select base</translation>
    </message>
    <message>
        <source>Pliki reguł(*.rul);; Pliki tekstowe (*.txt)</source>
        <translation type="vanished">Rule files(*.rul);; Text files (*.txt)</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="60"/>
        <source>log.applicationStart</source>
        <translation>Application CluVis started.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="90"/>
        <location filename="Forms/mainwindow.cpp" line="100"/>
        <source>log.failedToLoadObjBase</source>
        <translation>Failed to load object base.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="91"/>
        <source>log.noFileSelected</source>
        <translation>No file has been selected.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="101"/>
        <source>log.selectedFileIsNotKnowledgeBase</source>
        <translation>Selected file is not RSES knowledge base.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="111"/>
        <source>bold.ungrouped</source>
        <translation>&lt;b&gt;(Ungrouped)&lt;/b&gt;</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="124"/>
        <source>log.knowledgeBaseLoaded</source>
        <translation>Knowledge base loaded.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="142"/>
        <source>FD.selectKnowledgeBase</source>
        <translation>Select object base</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="144"/>
        <source>FD.RSESRules.fileTypes</source>
        <translation>RSES Rule files (*.rul);; Text files (*.txt)</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="191"/>
        <source>FD.save</source>
        <translation>Save</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="193"/>
        <source>FD.png</source>
        <translation>*.png</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="198"/>
        <source>log.failedToSaveVisualization</source>
        <translation>Failed to save visualization.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="199"/>
        <location filename="Forms/mainwindow.cpp" line="285"/>
        <source>log.fileNameNotSelected</source>
        <translation>No file name has been selected.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="221"/>
        <source>log.visualizationSavedWithName</source>
        <translation>Visuzalization saved with name %1.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="237"/>
        <location filename="Forms/mainwindow.cpp" line="253"/>
        <source>log.operationAborted</source>
        <translation>Operation aborted.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="248"/>
        <source>log.reportGenerationStarted</source>
        <translation>Report generation started.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="252"/>
        <source>log.unableToOpenFileForSaving</source>
        <translation>Unable to open file for saving.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="266"/>
        <source>log.reportGenerationFinished</source>
        <translation>Report generation finished.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="276"/>
        <source>FD.saveReport</source>
        <translation>Save report</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="278"/>
        <source>FD.reportFileTypes</source>
        <translation>XML Files (*.xml);; Text files (*.txt)</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="283"/>
        <source>log.failedToSaveReport</source>
        <translation>Failed to save report.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="346"/>
        <source>report.report</source>
        <translation>Report</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="348"/>
        <source>report.knowledgeBaseInformation</source>
        <translation>Object base information</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="350"/>
        <location filename="Forms/mainwindow.cpp" line="645"/>
        <source>report.nameOfBase</source>
        <translation>Name of the base</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="353"/>
        <location filename="Forms/mainwindow.cpp" line="646"/>
        <source>report.attributesNumber</source>
        <translation>Attributes number</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="356"/>
        <location filename="Forms/mainwindow.cpp" line="647"/>
        <source>report.objectsNumber</source>
        <translation>Objects number</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="359"/>
        <location filename="Forms/mainwindow.cpp" line="649"/>
        <source>report.clustersNumber</source>
        <translation>Clusters number</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="362"/>
        <location filename="Forms/mainwindow.cpp" line="650"/>
        <source>report.coverageSum</source>
        <translation>Coverage sum</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="365"/>
        <source>report.settings</source>
        <translation>Settings</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="367"/>
        <location filename="Forms/mainwindow.cpp" line="652"/>
        <source>report.groupingAlgorithmUsed</source>
        <translation>Clustering Algorithm used</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="370"/>
        <location filename="Forms/mainwindow.cpp" line="653"/>
        <source>report.objectsSimilarityMeasure</source>
        <translation>Objects similarity measure</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="373"/>
        <location filename="Forms/mainwindow.cpp" line="654"/>
        <source>report.clustersSimilarityMeasure</source>
        <translation>Clusters similarity measure</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="376"/>
        <location filename="Forms/mainwindow.cpp" line="651"/>
        <source>report.selectedVisualizationAlgorithm</source>
        <translation>Selected visualization algorithm</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="379"/>
        <location filename="Forms/mainwindow.cpp" line="655"/>
        <source>report.groupedRulePart</source>
        <translation>Grouped rule part</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="382"/>
        <source>report.clustersInformation</source>
        <translation>Clusters information</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="384"/>
        <location filename="Forms/mainwindow.cpp" line="656"/>
        <source>report.biggestCluster</source>
        <translation>The biggest cluster</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="387"/>
        <location filename="Forms/mainwindow.cpp" line="659"/>
        <source>report.smallestCluster</source>
        <translation>The smallest cluster</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="390"/>
        <source>report.clustersDetails</source>
        <translation>Cluster&apos;s details</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="395"/>
        <location filename="Forms/mainwindow.cpp" line="746"/>
        <source>report.clustersName</source>
        <translation>Cluster&apos;s name</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="398"/>
        <location filename="Forms/mainwindow.cpp" line="747"/>
        <source>report.clustersSize</source>
        <translation>Cluster&apos;s size</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="401"/>
        <location filename="Forms/mainwindow.cpp" line="751"/>
        <source>report.clustersCoverage</source>
        <translation>Cluster&apos;s coverage</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="657"/>
        <source>report.biggestClusterSize</source>
        <translation>Biggest cluster size</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="658"/>
        <source>report.biggestClusterRepLength</source>
        <translation>Biggest representative length</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="661"/>
        <source>report.biggestRepSize</source>
        <translation>Biggest representative size</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="662"/>
        <source>report.smallestRepSize</source>
        <translation>Smallest representative size</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="663"/>
        <source>report.averageRepSize</source>
        <translation>Average representative size</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="666"/>
        <source>report.minMDI</source>
        <translation>min. MDI</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="667"/>
        <source>report.minMDIClustersNumber</source>
        <translation>min. MDI Clusters number</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="753"/>
        <source>report.clustersRepresentative</source>
        <translation>Cluster&apos;s representative</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="409"/>
        <source>report.end</source>
        <translation>The end</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="644"/>
        <location filename="Forms/mainwindow.cpp" line="745"/>
        <source>report.index</source>
        <translation>Index</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="648"/>
        <source>report.nodesNumber</source>
        <translation>Nodes number</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="660"/>
        <source>report.ungroupedRules</source>
        <translation>Ungrouped objects</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="664"/>
        <source>report.MDI</source>
        <translation>MDI</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="665"/>
        <source>report.MDBI</source>
        <translation>MDBI</translation>
    </message>
    <message>
        <source>report.maxMDI</source>
        <translation type="vanished">Max. MDI</translation>
    </message>
    <message>
        <source>report.maxMDIClustersNumber</source>
        <translation type="vanished">Max MDI Clusters Number</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="668"/>
        <source>report.maxMDBI</source>
        <translation>Max. MDBI</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="669"/>
        <source>report.maxMDBIClustersNumber</source>
        <translation>Max. MDBI Clusters Number</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="748"/>
        <source>report.clustersRulesPercent</source>
        <translation>Objects percent in cluster [%]</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="749"/>
        <source>report.clustersNodesNumber</source>
        <translation>Cluster&apos;s nodes number</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="750"/>
        <source>report.clustersNodesNumberPercent</source>
        <translation>Cluster&apos;s nodes percent [%]</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="752"/>
        <source>report.clustersCoveragePercent</source>
        <translation>Cluster&apos;s coverage percent [%]</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="754"/>
        <source>report.representativeLength</source>
        <translation>Cluster&apos;s representative length</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="856"/>
        <source>log.programmeInformationOpened</source>
        <translation>Application information opened.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="862"/>
        <source>log.loadingGroupingSettings</source>
        <translation>Loading grouping settings...</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="866"/>
        <source>log.validatingSettings</source>
        <translation>Validating loaded settings...</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="870"/>
        <source>log.settingsCorrect</source>
        <translation>Settings are correct.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="880"/>
        <source>log.loadingVisualizationSettings</source>
        <translation>Loading visualization settings...</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="894"/>
        <source>log.visualizationSettingsLoaded</source>
        <translation>Visualization settings loaded.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="900"/>
        <source>log.visualizationGenerationFailed</source>
        <translation>Visualization generation failed.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="901"/>
        <source>log.objectsNotGrouped</source>
        <translation>Objects are not properly clustered.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="926"/>
        <location filename="Forms/mainwindow.cpp" line="971"/>
        <source>log.generalSettingsLoaded</source>
        <translation>General settings loaded.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="950"/>
        <source>log.rsesRules.detailedSettingsLoaded</source>
        <translation>RSES Rules detailed settings loaded.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="981"/>
        <source>report.detailedSettingsLoaded</source>
        <translation>Detailed settings loaded.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="1022"/>
        <location filename="Forms/mainwindow.cpp" line="1032"/>
        <source>log.failedAttemptOfGrouping</source>
        <translation>Failed attempt of clustering.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="1004"/>
        <source>log.baseNotSelected</source>
        <translation>Objects base is not selected.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="1023"/>
        <source>log.stopConditionToHigh</source>
        <translation>Stop condition cannot exceed objects number.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="1033"/>
        <source>log.stopConditionToSmall</source>
        <translation>Stop condition cannot be lower than 1.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="1048"/>
        <source>log.groupingStarted</source>
        <translation>Grouping started.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="1050"/>
        <location filename="Forms/mainwindow.cpp" line="1110"/>
        <source>log.blockingButtonsForOperation</source>
        <translation>Buttons shall be blocked during execution of operation.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="1057"/>
        <source>log.groupingThreadStarted</source>
        <translation>Grouping thread started.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="1064"/>
        <source>log.groupingThreadFinishedIn</source>
        <translation>Grouping thread executed in %1 ms.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="1072"/>
        <location filename="Forms/mainwindow.cpp" line="1138"/>
        <source>log.buttonsUnlocked</source>
        <translation>Buttons has been unlocked.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="1079"/>
        <source>FD.clustersNumber</source>
        <translation>Resultant clusters number</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="1082"/>
        <source>FD.clustersMDI</source>
        <translation>Resultant clusters MDI</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="1085"/>
        <source>FD.clustersMDBI</source>
        <translation>Resultant clusters MDBI</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="1089"/>
        <source>FD.visualizeGrouping</source>
        <translation>Do you want to visualize resultant structure of clustering?</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="1092"/>
        <location filename="Forms/mainwindow.cpp" line="1094"/>
        <source>FD.groupingFinished</source>
        <translation>Clustering finished</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="1097"/>
        <source>FD.yes</source>
        <translation>Yes</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="1098"/>
        <source>FD.no</source>
        <translation>No</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="1108"/>
        <source>log.visualizationStarted</source>
        <translation>Visualizing started.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="1115"/>
        <source>log.visualizationThreadStarted</source>
        <translation>Visualization thread started.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="1121"/>
        <source>log.visualizationThreadFinishedIn</source>
        <translation>Visualization thread finished in %1 ms.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="1132"/>
        <source>log.visualizationCentered</source>
        <translation>Visualization has been centered.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="1142"/>
        <source>FD.visualizationFinished.title</source>
        <translation>Visualization finished</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="1143"/>
        <source>FD.visualizationFinished.msg</source>
        <oldsource>log.visualizationFinished.msg</oldsource>
        <translation>Visualization finished!</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="1152"/>
        <source>log.groupedObjectsReceived</source>
        <translation>Grouped objects received.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="1154"/>
        <source>log.visualizationAvailable</source>
        <translation>Visualization is now available.</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="1160"/>
        <source>bold.grouped</source>
        <translation>&lt;b&gt;(Grouped)&lt;/b&gt;</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="1202"/>
        <source>log.clusterSelectedForVisualization</source>
        <translation>Cluster has been selected... Visualizing...</translation>
    </message>
    <message>
        <location filename="Forms/mainwindow.cpp" line="1214"/>
        <source>log.showClustersInfo</source>
        <translation>Showing info about selected cluster.</translation>
    </message>
</context>
<context>
    <name>QObject</name>
    <message>
        <location filename="Forms/mainwindow.cpp" line="1003"/>
        <source>log.failedAttemptOfGrouping</source>
        <translation>Failed attempt of clustering.</translation>
    </message>
</context>
<context>
    <name>clusterInfo_RSESRules</name>
    <message>
        <location filename="Forms/clusterinfo_rsesrules.ui" line="32"/>
        <source>Dialog</source>
        <translation>titlePlaceholder</translation>
    </message>
    <message>
        <location filename="Forms/clusterinfo_rsesrules.ui" line="48"/>
        <source>Liczba reguł w skupieniu:</source>
        <translation>Number of rules in cluster:</translation>
    </message>
    <message>
        <location filename="Forms/clusterinfo_rsesrules.ui" line="61"/>
        <source>liczba reguł</source>
        <translation>rulesNumPlaceholder</translation>
    </message>
    <message>
        <location filename="Forms/clusterinfo_rsesrules.ui" line="95"/>
        <source>Wizualizuj!</source>
        <translation>Visualize!</translation>
    </message>
    <message>
        <location filename="Forms/clusterinfo_rsesrules.ui" line="110"/>
        <source>Reprezentant skupienia:</source>
        <translation>Cluster&apos;s representative:</translation>
    </message>
    <message>
        <location filename="Forms/clusterinfo_rsesrules.ui" line="135"/>
        <source>reprezentant</source>
        <translation>repPlaceholder</translation>
    </message>
    <message>
        <location filename="Forms/clusterinfo_rsesrules.ui" line="164"/>
        <source>Atrybuty warunkowe występujące w skupieniu:</source>
        <translation>Conditional attributes occuring in cluster:</translation>
    </message>
    <message>
        <location filename="Forms/clusterinfo_rsesrules.ui" line="183"/>
        <location filename="Forms/clusterinfo_rsesrules.ui" line="212"/>
        <source>Atrybuty</source>
        <translation>attrPlaceholder</translation>
    </message>
    <message>
        <location filename="Forms/clusterinfo_rsesrules.ui" line="199"/>
        <source>Atrybuty decyzyjne występujące w skupieniu:</source>
        <translation>Decisional attributes occuring in cluster:</translation>
    </message>
    <message>
        <location filename="Forms/clusterinfo_rsesrules.ui" line="232"/>
        <source>Najdłuższa reguła:</source>
        <translation>Longest rule:</translation>
    </message>
    <message>
        <location filename="Forms/clusterinfo_rsesrules.ui" line="239"/>
        <location filename="Forms/clusterinfo_rsesrules.ui" line="268"/>
        <source>reguła</source>
        <translation>rulePlaceholder</translation>
    </message>
    <message>
        <location filename="Forms/clusterinfo_rsesrules.ui" line="255"/>
        <source>Najkrótsza reguła:</source>
        <translation>Shortest rule:</translation>
    </message>
    <message>
        <location filename="Forms/clusterinfo_rsesrules.ui" line="290"/>
        <source>Najczęstsza decyzja:</source>
        <translation>Most common decision:</translation>
    </message>
    <message>
        <location filename="Forms/clusterinfo_rsesrules.ui" line="303"/>
        <location filename="Forms/clusterinfo_rsesrules.ui" line="333"/>
        <source>decyzja</source>
        <translation>decisionPlaceholder</translation>
    </message>
    <message>
        <location filename="Forms/clusterinfo_rsesrules.ui" line="320"/>
        <source>Najrzadsza decyzja:</source>
        <translation>Least common decision:</translation>
    </message>
    <message>
        <location filename="Forms/clusterinfo_rsesrules.ui" line="350"/>
        <source>Wsparcie reguły:</source>
        <translation>Rule&apos;s support (for rules only):</translation>
    </message>
    <message>
        <location filename="Forms/clusterinfo_rsesrules.ui" line="363"/>
        <source>0</source>
        <translation>0</translation>
    </message>
    <message>
        <source>Informacje o skupieniu:</source>
        <translation type="vanished">Informations about cluster:</translation>
    </message>
    <message>
        <location filename="Forms/clusterinfo_rsesrules.cpp" line="19"/>
        <source>clusterInfo.clusterInfo</source>
        <translation>Information about cluster: </translation>
    </message>
</context>
<context>
    <name>groupingThread</name>
    <message>
        <location filename="Clustering/groupingthread.cpp" line="61"/>
        <location filename="Clustering/groupingthread.cpp" line="63"/>
        <source>gThreadDialog.grouping</source>
        <translation>Grouping...</translation>
    </message>
    <message>
        <location filename="Clustering/groupingthread.cpp" line="61"/>
        <location filename="Clustering/groupingthread.cpp" line="75"/>
        <source>gThreadDialog.cancel</source>
        <translation>Cancel</translation>
    </message>
    <message>
        <location filename="Clustering/groupingthread.cpp" line="74"/>
        <location filename="Clustering/groupingthread.cpp" line="77"/>
        <source>gThreadDialog.creatingSimilarityMatrix</source>
        <translation>Creating similarity matrix....</translation>
    </message>
    <message>
        <location filename="Clustering/groupingthread.cpp" line="92"/>
        <source>log.rsesGroupingStarted</source>
        <translation>RSES Rules grouping started...</translation>
    </message>
    <message>
        <location filename="Clustering/groupingthread.cpp" line="105"/>
        <source>log.unknownObjectsType</source>
        <translation>Unknown objects type.</translation>
    </message>
    <message>
        <location filename="Clustering/groupingthread.cpp" line="106"/>
        <source>log.operationWontStart</source>
        <translation>Operation won&apos;t start.</translation>
    </message>
    <message>
        <location filename="Clustering/groupingthread.cpp" line="115"/>
        <source>log.gatheringAttributesData</source>
        <translation>Gathering attributes data...</translation>
    </message>
    <message>
        <location filename="Clustering/groupingthread.cpp" line="122"/>
        <source>log.placingObjectsInClusters</source>
        <translation>Placing objects in clusters...</translation>
    </message>
    <message>
        <location filename="Clustering/groupingthread.cpp" line="128"/>
        <source>log.creatingSimMatrix</source>
        <translation>Creating similarity matrix...</translation>
    </message>
    <message>
        <location filename="Clustering/groupingthread.cpp" line="133"/>
        <source>log.groupingProcessStarted</source>
        <translation>Grouping process started.</translation>
    </message>
    <message>
        <location filename="Clustering/groupingthread.cpp" line="191"/>
        <source>log.clustersNumber</source>
        <translation>Clusters number: %1.</translation>
    </message>
    <message>
        <location filename="Clustering/groupingthread.cpp" line="196"/>
        <source>log.mdiPointer</source>
        <translation>MDI of grouping: %1.</translation>
    </message>
    <message>
        <location filename="Clustering/groupingthread.cpp" line="201"/>
        <source>log.mdbiPointer</source>
        <translation>MDBI of grouping: %1.</translation>
    </message>
    <message>
        <location filename="Clustering/groupingthread.cpp" line="205"/>
        <source>log.groupingFinished</source>
        <translation>Clustering  finished.</translation>
    </message>
    <message>
        <location filename="Clustering/groupingthread.cpp" line="206"/>
        <source>log.sendingResultatntStructure</source>
        <translation>Sending resultant structure to main thread...</translation>
    </message>
    <message>
        <location filename="Clustering/groupingthread.cpp" line="150"/>
        <source>log.groupingCancelled</source>
        <translation>Clustering cancelled.</translation>
    </message>
    <message>
        <location filename="Clustering/groupingthread.cpp" line="151"/>
        <source>log.visualizationImpossible</source>
        <translation>Visualization will be impossible until clustering is sucessfully completed.</translation>
    </message>
</context>
<context>
    <name>visualizationThread</name>
    <message>
        <location filename="Visualization/visualizationthread.cpp" line="30"/>
        <source>log.rsesVisualizationStarted</source>
        <translation>RSES Rules visualization started.</translation>
    </message>
    <message>
        <location filename="Visualization/visualizationthread.cpp" line="36"/>
        <source>log.unknownObjectsType</source>
        <translation>Unknown object type.</translation>
    </message>
    <message>
        <location filename="Visualization/visualizationthread.cpp" line="37"/>
        <source>log.operationWontStart</source>
        <translation>Operation won&apos;t start.</translation>
    </message>
</context>
</TS>
